-   id: xenon-cc
    name: Xenon CC
    description: Calculates Cyclomatic Complexity and fails any value < A.
    entry: xenon
    language: python
    types: [python]
    args: ["cc"]
    require_serial: false
    additional_dependencies: []
